<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Currency;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
	
    public function run(): void
    {
		
        $currencies = [
	['name' => 'USD','symbol' => '$',],
	['name' => 'VEF','symbol' => 'Bs.F',],
	['name' => 'CAD','symbol' => '$',],
	['name' => 'CHF','symbol' => 'CHF',],
	['name' => 'BRL','symbol' => 'R$',],
	['name' => 'CNY','symbol' => '¥',],
	['name' => 'CNH','symbol' => '¥',],
	['name' => 'COP','symbol' => '$',],
	['name' => 'CZK','symbol' => 'Kč',],
	['name' => 'DKK','symbol' => 'kr',],
	['name' => 'HUF','symbol' => 'Ft',],
	['name' => 'IDR','symbol' => 'Rp',],
	['name' => 'LVL','symbol' => 'Ls',],
	['name' => 'NOK','symbol' => 'kr',],
	['name' => 'XPF','symbol' => 'XPF',],
	['name' => 'PAB','symbol' => 'B/.',],
	['name' => 'PLN','symbol' => 'zł',],
	['name' => 'SEK','symbol' => 'kr',],
	['name' => 'ARS','symbol' => '$',],
	['name' => 'INR','symbol' => '₹',],
	['name' => 'AUD','symbol' => '$',],
	['name' => 'UAH','symbol' => '₴',],
	['name' => 'VND','symbol' => '₫',],
	['name' => 'HKD','symbol' => '$',],
	['name' => 'JPY','symbol' => '¥',],
	['name' => 'BGN','symbol' => 'лв',],
	['name' => 'LTL','symbol' => 'Lt',],
	['name' => 'RON','symbol' => 'lei',],
	['name' => 'HRK','symbol' => 'kn',],
	['name' => 'RUB','symbol' => 'руб',],
	['name' => 'TRY','symbol' => '₺',],
	['name' => 'KRW','symbol' => '₩',],
	['name' => 'MXN','symbol' => '$',],
	['name' => 'MYR','symbol' => 'RM',],
	['name' => 'NZD','symbol' => '$',],
	['name' => 'PHP','symbol' => '₱',],
	['name' => 'SGD','symbol' => 'S$',],
	['name' => 'ZAR','symbol' => 'R',],
	['name' => 'CRC','symbol' => '₡',],
	['name' => 'MUR','symbol' => 'Rs',],
	['name' => 'XOF','symbol' => 'CFA',],
	['name' => 'XAF','symbol' => 'FCFA',],
	['name' => 'UGX','symbol' => 'USh',],
	['name' => 'HNL','symbol' => 'L',],
	['name' => 'CLP','symbol' => '$',],
	['name' => 'UYU','symbol' => '$',],
	['name' => 'AFN','symbol' => 'Afs',],
	['name' => 'AOA','symbol' => 'Kz',],
	['name' => 'XCD','symbol' => '$',],
	['name' => 'AMD','symbol' => 'դր.',],
	['name' => 'AWG','symbol' => 'Afl.',],
	['name' => 'AZN','symbol' => 'm',],
	['name' => 'BSD','symbol' => 'B$',],
	['name' => 'BHD','symbol' => 'BD',],
	['name' => 'BDT','symbol' => '৳',],
	['name' => 'BBD','symbol' => 'Bds$',],
	['name' => 'BYR','symbol' => 'BR',],
	['name' => 'BYN','symbol' => 'Br',],
	['name' => 'BZD','symbol' => 'BZ$',],
	['name' => 'BMD','symbol' => 'BD$',],
	['name' => 'BTN','symbol' => 'Nu.',],
	['name' => 'BOB','symbol' => 'Bs.',],
	['name' => 'BAM','symbol' => 'KM',],
	['name' => 'BWP','symbol' => 'P',],
	['name' => 'BIF','symbol' => 'FBu',],
	['name' => 'KHR','symbol' => '៛',],
	['name' => 'KYD','symbol' => '$',],
	['name' => 'KMF','symbol' => 'CF',],
	['name' => 'CDF','symbol' => 'Fr',],
	['name' => 'CUP','symbol' => '$',],
	['name' => 'ANG','symbol' => 'ƒ',],
	['name' => 'DJF','symbol' => 'Fdj',],
	['name' => 'DOP','symbol' => 'RD$',],
	['name' => 'EGP','symbol' => 'LE',],
	['name' => 'SVC','symbol' => '¢',],
	['name' => 'ERN','symbol' => 'Nfk',],
	['name' => 'ETB','symbol' => 'Br',],
	['name' => 'FKP','symbol' => '£',],
	['name' => 'FJD','symbol' => 'FJ$',],
	['name' => 'GEL','symbol' => 'ლ',],
	['name' => 'GIP','symbol' => '£',],
	['name' => 'GNF','symbol' => 'FG',],
	['name' => 'GYD','symbol' => '$',],
	['name' => 'HTG','symbol' => 'G',],
	['name' => 'ISK','symbol' => 'kr',],
	['name' => 'IRR','symbol' => '﷼',],
	['name' => 'IQD','symbol' => ' ع.د',],
	['name' => 'ILS','symbol' => '₪',],
	['name' => 'JMD','symbol' => '$',],
	['name' => 'JOD','symbol' => ' د.ا ',],
	['name' => 'KZT','symbol' => '₸',],
	['name' => 'KES','symbol' => 'KSh',],
	['name' => 'KWD','symbol' => ' د.ك ',],
	['name' => 'KGS','symbol' => 'лв',],
	['name' => 'LAK','symbol' => '₭',],
	['name' => 'LBP','symbol' => 'ل.ل',],
	['name' => 'LSL','symbol' => 'M',],
	['name' => 'LRD','symbol' => 'L$',],
	['name' => 'LYD','symbol' => ' ل.د ',],
	['name' => 'MOP','symbol' => 'MOP$',],
	['name' => 'MKD','symbol' => 'ден',],
	['name' => 'MGA','symbol' => 'Ar',],
	['name' => 'MWK','symbol' => 'MK',],
	['name' => 'MVR','symbol' => 'Rf',],
	['name' => 'MRO','symbol' => 'UM',],
	['name' => 'MRU','symbol' => 'UM',],
	['name' => 'MDL','symbol' => 'L',],
	['name' => 'MNT','symbol' => '₮',],
	['name' => 'MAD','symbol' => 'DH',],
	['name' => 'BND','symbol' => '$',],
	['name' => 'DZD','symbol' => 'DA',],
	['name' => 'GHS','symbol' => 'GH¢',],
	['name' => 'GMD','symbol' => 'D',],
	['name' => 'MZN','symbol' => 'MT',],
	['name' => 'MMK','symbol' => 'K',],
	['name' => 'NAD','symbol' => '$',],
	['name' => 'NPR','symbol' => '₨',],
	['name' => 'ALL','symbol' => 'L',],
	['name' => 'NIO','symbol' => 'C$',],
	['name' => 'NGN','symbol' => '₦',],
	['name' => 'KPW','symbol' => '₩',],
	['name' => 'ZIG','symbol' => 'ZiG',],
	['name' => 'ZMW','symbol' => 'ZK',],
	['name' => 'YER','symbol' => '﷼',],
	['name' => 'EUR','symbol' => '€',],
	['name' => 'VUV','symbol' => 'VT',],
	['name' => 'UZS','symbol' => 'лв',],
	['name' => 'AED','symbol' => 'د.إ',],
	['name' => 'TMT','symbol' => 'T',],
	['name' => 'TND','symbol' => 'DT',],
	['name' => 'TTD','symbol' => '$',],
	['name' => 'TOP','symbol' => 'T$',],
	['name' => 'THB','symbol' => '฿',],
	['name' => 'TZS','symbol' => 'TSh',],
	['name' => 'TJS','symbol' => 'TJS',],
	['name' => 'TWD','symbol' => 'NT$',],
	['name' => 'SYP','symbol' => '£',],
	['name' => 'SZL','symbol' => 'E',],
	['name' => 'SRD','symbol' => '$',],
	['name' => 'SDG','symbol' => 'ج.س.',],
	['name' => 'LKR','symbol' => 'Rs',],
	['name' => 'SSP','symbol' => '£',],
	['name' => 'GBP','symbol' => '£',],
	['name' => 'SOS','symbol' => 'Sh.',],
	['name' => 'SBD','symbol' => 'SI$',],
	['name' => 'SLL','symbol' => 'Le',],
	['name' => 'SLE','symbol' => 'Le',],
	['name' => 'SCR','symbol' => 'SR',],
	['name' => 'RSD','symbol' => 'din.',],
	['name' => 'SAR','symbol' => 'SR',],
	['name' => 'STD','symbol' => 'Db',],
	['name' => 'WST','symbol' => 'WS$',],
	['name' => 'SHP','symbol' => '£',],
	['name' => 'RWF','symbol' => 'RF',],
	['name' => 'QAR','symbol' => 'QR',],
	['name' => 'PEN','symbol' => 'S/',],
	['name' => 'PYG','symbol' => '₲',],
	['name' => 'PGK','symbol' => 'K',],
	['name' => 'PKR','symbol' => 'Rs.',],
	['name' => 'OMR','symbol' => 'ر.ع.',],
	['name' => 'CVE','symbol' => '$',],
	['name' => 'COU','symbol' => '$',],
	['name' => 'CLF','symbol' => '$',],
	['name' => 'CUC','symbol' => '$',],
	['name' => 'GTQ','symbol' => 'Q',],
	['name' => 'VES','symbol' => 'Bs',],
	['name' => 'UYW','symbol' => '$',],
	['name' => 'UYI','symbol' => '$',],
	['name' => 'STN','symbol' => 'Db',],
];
        foreach ($currencies as $currency) {
            Currency::firstOrCreate([
                'name' => $currency['name'],
                'symbol' => $currency['symbol'],
            ]);
        }
    }
}
